---
- name: Install LAMP stack
  hosts: slave
  become: true
  tasks:
    - name: Copy bash script to Slave node
      copy:
        src: /home/vagrant/lamp_bash.sh
        dest: /home/vagrant/lamp_bash.sh
        mode: 0755

    - name: Execute bash script to setup LAMP stack
      command: /home/vagrant/lamp_bash.sh

    - name: Create cron job to check uptime every day at midnight
      cron:
        name: "uptime check"
        minute: "0"
        hour: "0"
        job: "/usr/bin/uptime >> /home/vagrant/uptime.log"

    - name: Verify PHP application accessibility
      #shell: "curl http://192.168.33.10/var/www/laravel"
      uri:
        url: http://192.168.33.10/var/www/laravel"
      register: result
      ignore_errors: true

    - name: Show output debug
      debug:
        var: result
